services:
  backend:
    build: ./backend
    environment:
      - MONGO_URI=${MONGO_URI}
      - DEFAULT_ADMIN_EMAIL=${DEFAULT_ADMIN_EMAIL}
      - DEFAULT_ADMIN_PASSWORD=${DEFAULT_ADMIN_PASSWORD}
    volumes:
      - ./data:/data
    ports:
      - "3000:3000"
    depends_on:
      mongodb:
        condition: service_healthy

  mongodb:
    image: mongo:8.0
    container_name: mongodb
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
    volumes:
      - mongodb_data:/data/db      # <-- À AJOUTER
    healthcheck:
      test: ["CMD", "pgrep", "mongod"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  mongodb_data:
