version: '3.8'

services:
  backend:
    build: ./
    environment:
      MONGO_URI: mongodb://root:example@mongodb:27017/app_elec?authSource=admin
    ports:
      - "3000:3000"
    depends_on:
      mongodb:
        condition: service_healthy

  mongodb:
    image: mongo:8.0
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
