version: '3.8'

services:
  backend:
    build: ./
    environment:
      - MONGO_URI=${MONGO_URI}
    ports:
      - "3000:3000"
    depends_on:
      mongodb:
        condition: service_healthy

  mongodb:
    image: mongo:8.0
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - mongodb_data:/data/db
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh --quiet -u root -p example localhost:27017/test | grep 1
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  mongodb_data:
